In [3]:
%pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in .\miniconda3\envs\notebook-env\Lib\site-packages (from seaborn) (2.5.1)
Requirement already satisfied: pandas>=1.2 in .\miniconda3\envs\notebook-env\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in .\miniconda3\envs\notebook-env\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in .\miniconda3\envs\notebook-env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\miniconda3\envs\notebook-env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\miniconda3\envs\notebook-env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\miniconda3\envs\notebook-env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\miniconda3\envs\notebook-env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=9 in .\miniconda3\envs\notebook-env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\miniconda3\envs\notebook-env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\miniconda3\envs\notebook-env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in .\miniconda3\envs\notebook-env\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in .\miniconda3\envs\notebook-env\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install pandas openpyxl

Requirement already satisfied: pandas in .\miniconda3\envs\notebook-env\Lib\site-packages (3.0.5)
Requirement already satisfied: openpyxl in .\miniconda3\envs\notebook-env\Lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=2.3.3 in .\miniconda3\envs\notebook-env\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\miniconda3\envs\notebook-env\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\miniconda3\envs\notebook-env\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: et-xmlfile in .\miniconda3\envs\notebook-env\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in .\miniconda3\envs\notebook-env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Load all sheets into a dictionary
file_path = "C:/Users/wellw/Downloads/DATASET_SOLTRACK/SOLTRACK_January_2025.xlsx"
sheets = pd.read_excel(file_path, sheet_name=None, engine='openpyxl')
# Check sheet names
print(sheets.keys())

dict_keys(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16', '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24', '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28', '2025-01-29', '2025-01-30', '2025-01-31'])

In [12]:
# Combine all sheets into one DataFrame
df = pd.concat(sheets.values(), ignore_index=True)
#The data is split across multiple days (Jan 1, Jan 2, Jan 3, Jan 4). Each sheet is one day's worth of data.
#It's easier to work with one DataFrame instead of switching between sheets every time you want to analyze or visualize something.
# Check shape
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
df.head()

Rows: 77724, Columns: 12

,Index,Time Stamp,Time (s),Temperature (°C),Irradiance (W/m²),Humidity (%),LDR1 Top (V),LDR2 Right (V),LDR3 Down (V),LDR4 Left (V),Tracked Azimuth (deg),Tracked Zenith (deg)
0,1,2025-01-01 00:00:00,0,26.935707,12.998936,53.942462,0.000000,0.03204,0.084214,0.035055,69.129961,85.878934
1,2,2025-01-01 00:00:15,15,26.683066,0.000000,54.726498,0.000000,0.00000,0.075650,0.007008,89.737530,86.030850
2,3,2025-01-01 00:00:30,30,26.755107,0.000000,53.846696,0.047136,0.00000,0.000000,0.054710,86.611051,90.000000
3,4,2025-01-01 00:00:45,45,25.859434,2.005892,52.276270,0.147144,0.00000,0.048742,0.089915,101.312175,90.000000
4,5,2025-01-01 00:01:00,60,27.015102,18.170587,52.354471,0.056631,0.00000,0.275075,0.000000,99.080142,87.747829

In [13]:
# Drop Irradiance column (column E - index 4 in 0-based counting)
# First check column names
print(df.columns.tolist())

# Drop Irradiance
df = df.drop(columns=['Irradiance (W/m²)'])

# Verify removal
df.columns.tolist()

['Index', 'Time Stamp', 'Time (s)', 'Temperature (°C)', 'Irradiance (W/m²)', 'Humidity (%)', 'LDR1 Top (V)', 'LDR2 Right (V)', 'LDR3 Down (V)', 'LDR4 Left (V)', 'Tracked Azimuth (deg)', 'Tracked Zenith (deg)']

['Index',
 'Time Stamp',
 'Time (s)',
 'Temperature (°C)',
 'Humidity (%)',
 'LDR1 Top (V)',
 'LDR2 Right (V)',
 'LDR3 Down (V)',
 'LDR4 Left (V)',
 'Tracked Azimuth (deg)',
 'Tracked Zenith (deg)']

In [15]:
df.head(2)

,Index,Time Stamp,Time (s),Temperature (°C),Humidity (%),LDR1 Top (V),LDR2 Right (V),LDR3 Down (V),LDR4 Left (V),Tracked Azimuth (deg),Tracked Zenith (deg)
0,1,2025-01-01 00:00:00,0,26.935707,53.942462,0.0,0.03204,0.084214,0.035055,69.129961,85.878934
1,2,2025-01-01 00:00:15,15,26.683066,54.726498,0.0,0.00000,0.075650,0.007008,89.737530,86.030850

In [18]:
#Check for missing values
df.isnull().sum()

Index                    0
Time Stamp               0
Time (s)                 0
Temperature (°C)         0
Humidity (%)             0
LDR1 Top (V)             0
LDR2 Right (V)           0
LDR3 Down (V)            0
LDR4 Left (V)            0
Tracked Azimuth (deg)    0
Tracked Zenith (deg)     0
dtype: int64

In [19]:
df.head()

,Index,Time Stamp,Time (s),Temperature (°C),Humidity (%),LDR1 Top (V),LDR2 Right (V),LDR3 Down (V),LDR4 Left (V),Tracked Azimuth (deg),Tracked Zenith (deg)
0,1,2025-01-01 00:00:00,0,26.935707,53.942462,0.000000,0.03204,0.084214,0.035055,69.129961,85.878934
1,2,2025-01-01 00:00:15,15,26.683066,54.726498,0.000000,0.00000,0.075650,0.007008,89.737530,86.030850
2,3,2025-01-01 00:00:30,30,26.755107,53.846696,0.047136,0.00000,0.000000,0.054710,86.611051,90.000000
3,4,2025-01-01 00:00:45,45,25.859434,52.276270,0.147144,0.00000,0.048742,0.089915,101.312175,90.000000
4,5,2025-01-01 00:01:00,60,27.015102,52.354471,0.056631,0.00000,0.275075,0.000000,99.080142,87.747829

In [20]:
df.to_csv('SOLTRACK_CLEANED.csv', index=False)

In [21]:
# Save to Desktop (Windows)
df.to_csv(r'C:\Users\wellw\Downloads\SOLTRACK_CLEANED.csv', index=False)